### ISSUE TITLE
Scheduling Interface should warn about double-booking rooms

### ISSUE THREAD

**Issue by dkapell** [neinteractiveliterature/intercode#2106] opened 2019-04-02 19:57 UTC
It would be good to have the scheduling interface raise a warning in realtime before submission if you double-book a room

**Comment by nbudin** [comment] 2019-05-25 15:19
I had a funny feeling this was a duplicate of something or other, and it's a duplicate of #1500.

**Closed by nbudin** 2019-05-25 15:19 UTC
Labels: duplicate
